### ISSUE TITLE
"Mathematics" dropdown should be clickable

### ISSUE THREAD

**Issue by calvinc404** [calvinc404/website#1]
On mobile, "Mathematics" cannot be clicked, meaning the dropdown cannot be accessed

**Comment by curtindolph-calvin-10** [comment]
What is the tag? Can the tag be clicked?

**Comment by curtindolph-calvin-10** [comment]
Changing the tag didn't fix the problem.

**Comment by calvinc404** [comment]
loading bootstrap from cdn rather than locally did it
